qtbase: disable tests that fail with gold linker
Some of the tests fail with gold linker.
error: unexpected reloc 3 against global symbol qt_version_tag without base register in object file when generating a position-independent output file
collect2: error: ld returned 1 exit status

Cherry-pick updated with more tests for dev.

Change-Id: I223e34fb9ecba01a8f3df5123eed6705d93ceed8
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>
(cherry picked from commit f45f237084ec35b86fc7086bdf47fa56a917dcb1)