packagegroups: enable workaround for allarch packagegroup
Enable workaround for the sanity check of allarch packagegroups
which caused
ERROR: nativesdk-packagegroup-qt6-toolchain-host-essentials-1.0-r0
  do_package_write_rpm: An allarch packagegroup shouldn't depend on
  packages which are dynamically renamed (nativesdk-qttools-dev
  to nativesdk-libqt6uitools-dev)

Nativesdk changes the PACKAGE_ARCH correctly, but it cannot be
inherited first because that would throw another sanity warning.

Pick-to: 6.5 6.2
Fixes: QTBUG-113178
Change-Id: Ifd77ef76f37b9fe39ef38adcc28c87130bf6d6d4
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>