qt3d: Backport assimp fix for build with gcc-13
* fixes:
  http://errors.yoctoproject.org/Errors/Details/704200/

  qt3d/6.5.0-r0/git/src/3rdparty/assimp/src/code/AssetLib/FBX/FBXBinaryTokenizer.cpp:475:61: error: 'uint32_t' is not a member of 'std'; did you mean 'wint_t'?
    475 |         if (!is64bits && (length > std::numeric_limits<std::uint32_t>::max())) {
        |                                                             ^~~~~~~~
        |                                                             wint_t

Change-Id: I503f18ae93a24fe08b66827b4ab2dc5b7562819a
Reviewed-by: Martin Jansa <Martin.Jansa@gmail.com>
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>
(cherry picked from commit e1cacf710fe005c7a830f0f51e672ee77d3ba418)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>