qtmultimedia: inherit pkgconfig
Newer oe-core doesn't pull many default dependencies anymore:
https://lists.openembedded.org/g/openembedded-core/message/156185
add explicit dependency on pkgconfig through pkgconfig.bbclass as
we're using it here.

Fixes:
ERROR: Feature 'pulseaudio' was enabled, but the pre-condition 'libs.pulseaudio' failed.

Similar change was already applied in meta-qt5:
https://github.com/meta-qt5/meta-qt5/commit/f200be9d671ced4d2f8054c238527a7c6ed5b4b8
but the same is needed for qt6.

Change-Id: Ic3f674bcfd7dbbc6f149a1ae94cd66613a948050
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>
(cherry picked from commit d718354d16d1e65b0d02b360f56d23f56d083d69)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>