qtbase: avoid cmake archiving api for native build
After 812bf25183c440dd28dcadaa7732d8f088b134f1, we need to extend the
workaround for badly configured CMake also to qtbase-native. This fixes
error: CMake was not built with zstd support. Rebuild CMake or
set QT_AVOID_CMAKE_ARCHIVING_API=ON.

Fixes: WEBOSCI-54
Change-Id: I33c97b1a051fe90d706461c83f75912aa1c1c820
Reviewed-by: Janne Juntunen <janne.juntunen@qt.io>
(cherry picked from commit 0bb5361fe0495e23e451869fc10faeb29a825571)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>