qtbase: inherit pkgconfig
Newer oe-core doesn't pull many default dependencies anymore:
https://lists.openembedded.org/g/openembedded-core/message/156185
add explicit dependency on pkgconfig through webos_pkgconfig.bbclass as
we're using it here.

Fixes:
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
...
ERROR: Feature "zstd": Forcing to "ON" breaks its condition:
ERROR: Feature "libudev": Forcing to "ON" breaks its condition:

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Change-Id: I0705e15d57f30b5aeb908631d269db3dfd3413f3