srcrev_update: fix update task with latest fetcher
Additional check was added into the bb.fetcher that needs to be
workaround in srcrev_update task. Otherwise task will fail with
error:

Exception: bb.fetch2.FetchError: Fetcher failure: Recipe uses a
floating tag/branch without a fixed SRCREV yet doesn't call
bb.fetch2.get_srcrev() (use SRCPV in PV for OE).

Pick-to: 6.3 6.2
Change-Id: Ib3c2665257c344c312074519a03d96437866cd8d
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>