qtbase: remove runtime dependency to libssl from native package
This a workaround for Dunfell, where native packages are still
cleared which means that qtbase-native cannot have runtime dependency
to libssl as the package does not exist.

Fixes:
ERROR: Required build target 'qtbase-native' has no buildable providers.
Missing or unbuildable dependency chain was: ['qtbase-native', 'libssl-native']

Pick-to: 6.2
Change-Id: Idad2a85b3a84275e5824545e22d425b578d1d647
Reviewed-by: Pasi Petäjäjärvi <pasi.petajajarvi@qt.io>