packagegroup-qt6-commercial-modules: include qt6-commercial.inc
* all rdepends are skipped without Commercial Qt, make sure the
  packagegroup is skipped as well

* fixes:
  ERROR: Nothing RPROVIDES 'qmlcompilerplus' (but meta-qt6/recipes-qt/packagegroups/packagegroup-qt6-commercial-modules.bb RDEPENDS on or otherwise requires it)
  qmlcompilerplus was skipped: Available only with Commercial Qt
  NOTE: Runtime target 'qmlcompilerplus' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['qmlcompilerplus']
  ERROR: Nothing RPROVIDES 'qtvncserver' (but meta-qt6/recipes-qt/packagegroups/packagegroup-qt6-commercial-modules.bb RDEPENDS on or otherwise requires it)
  qtvncserver was skipped: Available only with Commercial Qt
  NOTE: Runtime target 'qtvncserver' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['qtvncserver']

Pick-to: 6.5 6.4
Change-Id: I373c034989a643b5e95f84deb5130580201eddea
Reviewed-by: Martin Jansa <Martin.Jansa@gmail.com>
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>