Coin: fetch repo from github
Git clones from google fail frequently with:
   >> fatal: early EOF
   >> error: index-pack died
Switch to using github mirror for the git-repo repository.

Pick-to: 6.5 6.5.0 6.4 6.4.3 6.2
Change-Id: Id0cbf3c59e50869d62880e56251b003490c4c1ee
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>