qtwebengine: enable webrtc-pipewire only when multimedia-layer is included
* pipewire recipe is in meta-multimedia not meta-oe layer
* fixes:
  ERROR: Nothing PROVIDES 'pipewire' (but /OE/build/oe-core/meta-qt6/recipes-qt/qt6/qtwebengine_git.bb DEPENDS on or otherwise requires it)

Change-Id: I137c708ed7e186b4f4d5bbe921cccc7100db48b4
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>
(cherry picked from commit c4147feb79be999f244bac84fd69d10aa5ef09b4)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>