qtbase: fix rcc build
Add patch to fix rcc build:

| /usr/src/debug/qtbase/6.3.2-r0/git/src/tools/rcc/rcc.cpp:907: error: undefined reference to 'ZSTD_maxCLevel'
| /usr/src/debug/qtbase/6.3.2-r0/git/src/tools/rcc/rcc.cpp:487: error: undefined reference to 'ZSTD_freeCCtx'
| /usr/src/debug/qtbase/6.3.2-r0/git/src/tools/rcc/rcc.cpp:287: error: undefined reference to 'ZSTD_compressCCtx'
| /usr/src/debug/qtbase/6.3.2-r0/git/src/tools/rcc/rcc.cpp:298: error: undefined reference to 'ZSTD_isError'
| /usr/src/debug/qtbase/6.3.2-r0/git/src/tools/rcc/rcc.cpp:277: error: undefined reference to 'ZSTD_createCCtx'
| /usr/src/debug/qtbase/6.3.2-r0/git/src/tools/rcc/rcc.cpp:294: error: undefined reference to 'ZSTD_compressCCtx'
| /usr/src/debug/qtbase/6.3.2-r0/git/src/tools/rcc/rcc.cpp:300: error: undefined reference to 'ZSTD_getErrorName'
| collect2: error: ld returned 1 exit status

Change-Id: Iaa4d5c4ecb06d5a0244d6a746d5402d23d4ddd0e
Reviewed-by: Tarja Sundqvist <tarja.sundqvist@qt.io>
(cherry picked from commit adf0acfcd1adfc1e7dd7ff99e83e91bf911906f2)
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>